name: vet_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^6.0.0
  flutter_svg: ^2.0.10
  cupertino_icons: ^1.0.2
  http: ^1.3.0
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5
  
  # Firebase dependencies
  firebase_auth: ^5.1.0
  firebase_core: ^3.13.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/menu/
    - assets/icons/common/
    - assets/images/
    - assets/icons/common/logo.svg
    - assets/icons/common/google_button.svg
    - assets/images/grass_banner.jpg
    - assets/images/feed_topic1.jpg
    - assets/images/feed_topic2.jpg
    - assets/images/feed_topic3.jpg
    - assets/images/muzoo_banner.png
    - assets/images/insemination1.png
    - assets/images/insemination2.png
    - assets/images/insemination3.png
    - assets/images/disease_topic1.jpg
    - assets/images/disease_topic2.jpg
    - assets/images/disease_topic3.jpg
    - assets/images/bodomal_banner.png
    - assets/images/horses_banner.png
    - assets/images/horse_topic1.png
    - assets/images/horse_topic2.png
    - assets/images/horse_topic3.png
    - assets/images/sheep_banner.svg
    - assets/images/vet_profile.png
