// This file contains Firebase options for different platforms (iOS, web, macOS, Android, Windows). It is generated by FlutterFire CLI and should not be manually edited.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3-VHFTRO20WkOPzYmKvGmEvUT7Js4ENU',
    appId: '1:207573665237:ios:896b6e25d5638e56d0295c',
    messagingSenderId: '207573665237',
    projectId: 'vetapp-f8230',
    storageBucket: 'vetapp-f8230.firebasestorage.app',
    iosClientId: '207573665237-705bq7r1nre1p7508f3n9602o2ecpvbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetMobileApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFmqy12G_9Q4d_mVrzn0t6-HM__5Y5d60',
    appId: '1:207573665237:web:b22e095ad0f5b238d0295c',
    messagingSenderId: '207573665237',
    projectId: 'vetapp-f8230',
    authDomain: 'vetapp-f8230.firebaseapp.com',
    storageBucket: 'vetapp-f8230.firebasestorage.app',
    measurementId: 'G-GE8H1RNDRM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3-VHFTRO20WkOPzYmKvGmEvUT7Js4ENU',
    appId: '1:207573665237:ios:896b6e25d5638e56d0295c',
    messagingSenderId: '207573665237',
    projectId: 'vetapp-f8230',
    storageBucket: 'vetapp-f8230.firebasestorage.app',
    iosClientId: '207573665237-705bq7r1nre1p7508f3n9602o2ecpvbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.vetMobileApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE7qS90fhr5AcHx_hR-VUD0ranoqhM0vM',
    appId: '1:207573665237:android:b93a11c7f9c633c5d0295c',
    messagingSenderId: '207573665237',
    projectId: 'vetapp-f8230',
    storageBucket: 'vetapp-f8230.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFmqy12G_9Q4d_mVrzn0t6-HM__5Y5d60',
    appId: '1:207573665237:web:8cfe8ead2364731cd0295c',
    messagingSenderId: '207573665237',
    projectId: 'vetapp-f8230',
    authDomain: 'vetapp-f8230.firebaseapp.com',
    storageBucket: 'vetapp-f8230.firebasestorage.app',
    measurementId: 'G-E1GJCSC1FH',
  );

}